language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.6"
      install:
        - pip install pytest-flake8
        - pip install .
      script:
        - pytest --flake8 -m flake8
      after_success: []
install:
  - pip install pytest-cov codecov
  - pip install .
script:
  - pytest --cov=nuc_processing
after_success:
  - codecov
